reference_name_or_path: Qwen/Qwen2.5-1.5B
policy_name_or_path: Qwen/Qwen2.5-1.5B
teacher_name_or_path: Qwen/Qwen2.5-1.5B
student_name_or_path: Qwen/Qwen2.5-1.5B

teacher_tokenizer_name_or_path: null
student_tokenizer_name_or_path: null

policy_block_name: Qwen2DecoderLayer
reference_block_name: Qwen2DecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float32