name: DSKD-DPO_train

channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.11.11
  - numpy
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - pandas
  - matplotlib
  - pip=24.1.2
  - pip:
      - torch==2.6.0
      - torchvision==0.21.0
      - datasets==3.5.0
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - accelerate>=0.20.3
      - wandb>=0.15.4
      - tensor-parallel==1.3.0
      - langdetect==1.0.9
      - transformers>=4.31.0
      - sentencepiece>=0.1.99
  # - pip_args: --index-url https://download.pytorch.org/whl/cu124
